"""Initial migrations

Revision ID: 4ade8cda9051
Revises: 2633a5c1f215
Create Date: 2023-09-08 14:03:25.705734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ade8cda9051'
down_revision = '2633a5c1f215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
